DELIMITER $$
CALL crearUsuario('super1','admin','SUPER1','super',0);
CALL crearUsuario('super2','admin','SUPER2','super',0);
CALL crearUsuario('super3','admin','SUPER3','super',0);
CALL crearUsuario('admin1','admin','ADMIN1','admin',1);
CALL crearUsuario('admin2','admin','ADMIN2','admin',1);
CALL crearUsuario('admin3','admin','ADMIN3','admin',1);
CALL crearUsuario('user1','admin','USER1','user',2);
CALL crearUsuario('user2','admin','USER2','user',2);
CALL crearUsuario('user3','admin','USER3','user',2);
CALL crearTipoEstablecimiento('Hotel','Son hoteles...');
CALL crearTipoEstablecimiento('Restaurante','Son restaurantes');
CALL crearTipoEstablecimiento('Taller','Son talleres');
CALL crearTipoEstablecimiento('Iglesia','Son iglesias');
CALL crearTipoEstablecimiento('Hospital','Son hospitales');
CALL crearTipoEstablecimiento('Funeraria','Son funerarias...');
CALL crearTipoEstablecimiento('Universidad','Son universidades...');
CALL crearTipoServicio('Hospedaje','Renta de habitaciones.');
CALL crearTipoServicio('Spa','Servicios de relajacion.');
CALL crearTipoServicio('Tour','Recorridos y excursiones.');
CALL crearTipoServicio('Desayuno','Menus de desayuno.');
CALL crearTipoServicio('Almuerzo','Menus de almuerzo.');
CALL crearTipoServicio('Cena','Menus de cena.');
CALL crearTipoServicio('Reparacion','Reparacion de vehiculos.');
CALL crearTipoServicio('Servicio','Servicio preventivo de vehiculos.');
CALL crearTipoServicio('Pintura','Trabajos de enderezado y pintura.');
CALL crearTipoServicio('Boda','Servicios matrimoniales.');
CALL crearTipoServicio('Bautizos','Servicios de bautizo.');
CALL crearTipoServicio('Primera comunion','Servicios de primera comunion.');
CALL crearTipoServicio('Cirujia','Operaciones quirurjicas.');
CALL crearTipoServicio('Consulta','Consulte a un especialista.');
CALL crearTipoServicio('Revision','Regrese para checkeo.');
CALL crearTipoServicio('Entierro','Entierre los restos de sus seres queridos.');
CALL crearTipoServicio('Cremacion','Queme a sus seres queridos.');
CALL crearTipoServicio('Velorio','Servicios de velorios.');
CALL crearTipoServicio('Clase','Inscribete a una clase.');
CALL crearTipoServicio('Examen','Toma una prueba para validar tus conocimientos.');
CALL crearTipoServicio('Graduacion','Graduate de tus cursos.');
CALL crearCaracteristica('Vista al mar',0);
CALL crearCaracteristica('Baños europeo',0);
CALL crearCaracteristica('Sabanas egipcias',0);
CALL crearCaracteristica('Vista a los jardines',0);
CALL crearCaracteristica('Sin vista',0);
CALL crearCaracteristica('Duracion corta',30);
CALL crearCaracteristica('Duracion media',45);
CALL crearCaracteristica('Duracion larga',60);
CALL crearCaracteristica('Dietetico',0);
CALL crearCaracteristica('Grasoso',0);
CALL crearCaracteristica('Extra grande',0);
CALL crearCaracteristica('Pintura profesional',0);
CALL crearCaracteristica('Pintura standard',0);
CALL crearCaracteristica('Privado',0);
CALL crearCaracteristica('Compartido',0);
CALL crearCaracteristica('Nivel principiante',0);
CALL crearCaracteristica('Nivel medio',0);
CALL crearCaracteristica('Nivel avanzado',0);
CALL crearDimension('Clase 1');
CALL crearDimension('Clase 2');
CALL crearDimension('Clase 3');
CALL crearDimension('Clase 4');
CALL crearCategoria(1,'Caro');
CALL crearCategoria(1,'Grande');
CALL crearCategoria(1,'Interior');
CALL crearCategoria(2,'Caro');
CALL crearCategoria(2,'Pequeño');
CALL crearCategoria(2,'Exterior');
CALL crearCategoria(3,'Barato');
CALL crearCategoria(3,'Grande');
CALL crearCategoria(3,'Popular');
CALL crearCategoria(3,'Caro');
CALL crearCategoria(3,'Mediano');
CALL crearCategoria(3,'Interior y exterior');
CALL crearEstablecimiento('Conquistador','14.619974,-90.516157','Inserte descripcion del establecimiento aqui.',1,1);
CALL crearEstablecimiento('Vista Real','14.572025,-90.484886','Inserte descripcion del establecimiento aqui.',1,1);
CALL crearEstablecimiento('Radisson Suites','14.638434,-90.485146','Inserte descripcion del establecimiento aqui.',1,1);
CALL crearEstablecimiento('Intercontinental','14.598406,-90.514327','Inserte descripcion del establecimiento aqui.',1,1);
CALL crearEstablecimiento('Royal Palace','14.636692,-90.515124','Inserte descripcion del establecimiento aqui.',1,1);
CALL crearEstablecimiento('Hard Rock Cafe','14.599230,-90.515422','Inserte descripcion del establecimiento aqui.',2,1);
CALL crearEstablecimiento('Mc Donalds Zapote','14.651258,-90.516065','Inserte descripcion del establecimiento aqui.',2,1);
CALL crearEstablecimiento('LOsteria de Saul','14.602708,-90.511864','Inserte descripcion del establecimiento aqui.',2,1);
CALL crearEstablecimiento('Casa Escobal Antigua','14.557432,-90.735096','Inserte descripcion del establecimiento aqui.',2,1);
CALL crearEstablecimiento('Siebold','14.621831,-90.515370','Inserte descripcion del establecimiento aqui.',3,1);
CALL crearEstablecimiento('Cofiño Stahl','14.617826,-90.512139','Inserte descripcion del establecimiento aqui.',3,1);
CALL crearEstablecimiento('Talleres Porras','14.620585,-90.511668','Inserte descripcion del establecimiento aqui.',3,1);
CALL crearEstablecimiento('Talleres Aguilar','14.613812,-90.510929','Inserte descripcion del establecimiento aqui.',3,1);
CALL crearEstablecimiento('Cat. Metropolitana','14.641519,-90.512039','Inserte descripcion del establecimiento aqui.',4,1);
CALL crearEstablecimiento('La Merced','14.650755,-90.502092','Inserte descripcion del establecimiento aqui.',4,1);
CALL crearEstablecimiento('Sant. de Guadalupe','14.641491,-90.519370','Inserte descripcion del establecimiento aqui.',4,1);
CALL crearEstablecimiento('Templo Recoleccion','14.646840,-90.517108','Inserte descripcion del establecimiento aqui.',4,1);
CALL crearEstablecimiento('San Juan de Dios','14.639673,-90.521244','Inserte descripcion del establecimiento aqui.',5,1);
CALL crearEstablecimiento('Hospital Roosevelt','14.613726,-90.543058','Inserte descripcion del establecimiento aqui.',5,1);
CALL crearEstablecimiento('Hermano Pedro','14.603212,-90.559747','Inserte descripcion del establecimiento aqui.',5,1);
CALL crearEstablecimiento('Hospital Novicentro','14.601530,-90.562643','Inserte descripcion del establecimiento aqui.',5,1);
CALL crearEstablecimiento('Funerales Reforma','14.617187, -90.540205','Inserte descripcion del establecimiento aqui.',6,1);
CALL crearEstablecimiento('Capillas Señoriales','14.595996, -90.520432','Inserte descripcion del establecimiento aqui.',6,1);
CALL crearEstablecimiento('Capillas la Colina','14.591188, -90.544692','Inserte descripcion del establecimiento aqui.',6,1);
CALL crearEstablecimiento('San Carlos','14.587641, -90.553347','Inserte descripcion del establecimiento aqui.',7,1);
CALL crearEstablecimiento('Rafael Landivar','14.595122, -90.484263','Inserte descripcion del establecimiento aqui.',7,1);
CALL crearEstablecimiento('Francisco Marroquin','14.607252, -90.505535','Inserte descripcion del establecimiento aqui.',7,1);
CALL crearEstablecimiento('Mariano Galvez','14.659010, -90.513550','Inserte descripcion del establecimiento aqui.',7,1);
CALL crearEstablecimiento('Galileo','14.609670, -90.505735','Inserte descripcion del establecimiento aqui.',7,1);
CALL crearEstablecimiento('Hardvard','42.376464, -71.116649','Inserte descripcion del establecimiento aqui.',7,1);
CALL crearDimensionEstablecimiento(1,1);
CALL crearDimensionEstablecimiento(2,2);
CALL crearDimensionEstablecimiento(3,3);
CALL crearDimensionEstablecimiento(4,4);
CALL crearDimensionEstablecimiento(1,5);
CALL crearDimensionEstablecimiento(2,6);
CALL crearDimensionEstablecimiento(3,7);
CALL crearDimensionEstablecimiento(4,8);
CALL crearDimensionEstablecimiento(1,9);
CALL crearDimensionEstablecimiento(2,10);
CALL crearDimensionEstablecimiento(3,11);
CALL crearDimensionEstablecimiento(4,12);
CALL crearDimensionEstablecimiento(1,13);
CALL crearDimensionEstablecimiento(2,14);
CALL crearDimensionEstablecimiento(3,15);
CALL crearDimensionEstablecimiento(4,16);
CALL crearDimensionEstablecimiento(1,17);
CALL crearDimensionEstablecimiento(2,18);
CALL crearDimensionEstablecimiento(3,19);
CALL crearDimensionEstablecimiento(4,20);
CALL crearDimensionEstablecimiento(1,21);
CALL crearDimensionEstablecimiento(2,22);
CALL crearDimensionEstablecimiento(3,23);
CALL crearDimensionEstablecimiento(4,24);
CALL crearDimensionEstablecimiento(1,25);
CALL crearDimensionEstablecimiento(2,26);
CALL crearDimensionEstablecimiento(3,27);
CALL crearDimensionEstablecimiento(4,28);
CALL crearDimensionEstablecimiento(1,29);
CALL crearDimensionEstablecimiento(2,30);
CALL crearServicio('Habitacion simple',10,1,1);
CALL crearServicio('Masage relajante',10,1,2);
CALL crearServicio('Tour de la ciudad',10,1,3);
CALL crearServicio('Habitacion deluxe',10,2,1);
CALL crearServicio('Masage exfoliante',10,2,2);
CALL crearServicio('Tour de las ruinas',10,2,3);
CALL crearServicio('Habitacion doble',10,3,1);
CALL crearServicio('Masage relajante',10,3,2);
CALL crearServicio('Tour de la ciudad',10,3,3);
CALL crearServicio('Habitacion triple',10,4,1);
CALL crearServicio('Baño de vapor',10,4,2);
CALL crearServicio('Tour de la ciudad',10,4,3);
CALL crearServicio('Habitacion simple',10,5,1);
CALL crearServicio('Masage exfoliante',10,5,2);
CALL crearServicio('Safari',10,5,3);
CALL crearServicio('Huevos revueltos',10,6,4);
CALL crearServicio('Lasagna',10,6,5);
CALL crearServicio('Ensalada',10,6,6);
CALL crearServicio('Huevos estrellados',10,7,4);
CALL crearServicio('Pechuga de pollo',10,7,5);
CALL crearServicio('Pechuga grill',10,7,6);
CALL crearServicio('Huevo duro',10,8,4);
CALL crearServicio('Dobladas en salsa',10,8,5);
CALL crearServicio('Atol de elote',10,8,6);
CALL crearServicio('Huevos divorciados',10,9,4);
CALL crearServicio('Hilachas',10,9,5);
CALL crearServicio('Cocido de verduras',10,9,6);
CALL crearServicio('Reparacion frenos',10,10,7);
CALL crearServicio('Servicio menor',10,10,8);
CALL crearServicio('Pintura completa',10,10,9);
CALL crearServicio('Reparar suspension',10,11,7);
CALL crearServicio('Servicio mayor',10,11,8);
CALL crearServicio('Pintura 1 pieza',10,11,9);
CALL crearServicio('Reparacion motor',10,12,7);
CALL crearServicio('Servicio medio',10,12,8);
CALL crearServicio('Pintura especial',10,12,9);
CALL crearServicio('Reparacion cerradura',10,13,7);
CALL crearServicio('Servicio 10k',10,13,8);
CALL crearServicio('Pintura basica',10,13,9);
CALL crearServicio('Boda simple',10,14,10);
CALL crearServicio('Bautizo simple',10,14,11);
CALL crearServicio('Servicio rapido',10,14,12);
CALL crearServicio('Boda simple',10,15,10);
CALL crearServicio('Bautizo simple',10,15,11);
CALL crearServicio('Servicio rapido',10,15,12);
CALL crearServicio('Boda simple',10,16,10);
CALL crearServicio('Bautizo simple',10,16,11);
CALL crearServicio('Servicio rapido',10,16,12);
CALL crearServicio('Boda simple',10,17,10);
CALL crearServicio('Bautizo simple',10,17,11);
CALL crearServicio('Servicio rapido',10,17,12);
CALL crearServicio('Corazon abierto',10,18,13);
CALL crearServicio('Checkeo completo',10,18,14);
CALL crearServicio('Revision de rutina',10,18,15);
CALL crearServicio('Apendice',10,19,13);
CALL crearServicio('Checkeo medio',10,19,14);
CALL crearServicio('Revision urgente',10,19,15);
CALL crearServicio('Amigdalas',10,20,13);
CALL crearServicio('Checkeo completo',10,20,14);
CALL crearServicio('Revision estandar',10,20,15);
CALL crearServicio('Transplante',10,21,13);
CALL crearServicio('Checkeo medio',10,21,14);
CALL crearServicio('Revision de rutina',10,21,15);
CALL crearServicio('Entierro simple',10,22,16);
CALL crearServicio('Cremacion simple',10,22,17);
CALL crearServicio('Velorio simple',10,22,18);
CALL crearServicio('Entierro simple',10,23,16);
CALL crearServicio('Cremacion simple',10,23,17);
CALL crearServicio('Velorio simple',10,23,18);
CALL crearServicio('Entierro simple',10,24,16);
CALL crearServicio('Cremacion simple',10,24,17);
CALL crearServicio('Velorio simple',10,24,18);
CALL crearServicio('Clase principiante',10,25,19);
CALL crearServicio('Examen privado',10,25,20);
CALL crearServicio('Graduacion deluxe',10,25,21);
CALL crearServicio('Clase intermedia',10,26,19);
CALL crearServicio('Examen publico',10,26,20);
CALL crearServicio('Graduacion simple',10,26,21);
CALL crearServicio('Clase avanzada',10,27,19);
CALL crearServicio('Examen privado',10,27,20);
CALL crearServicio('Graduacion deluxe',10,27,21);
CALL crearServicio('Clase practica',10,28,19);
CALL crearServicio('Examen nivelacion',10,28,20);
CALL crearServicio('Graduacion rapida',10,28,21);
CALL crearServicio('Laboratorio',10,29,19);
CALL crearServicio('Examen privado',10,29,20);
CALL crearServicio('Graduacion full',10,29,21);
CALL crearServicio('Clase principiante',10,30,19);
CALL crearServicio('Examen nivelacion',10,30,20);
CALL crearServicio('Graduacion deluxe',10,30,21);
CALL crearDetalleServicio(1,1);
CALL crearDetalleServicio(2,2);
CALL crearDetalleServicio(3,3);
CALL crearDetalleServicio(4,4);
CALL crearDetalleServicio(5,5);
CALL crearDetalleServicio(6,6);
CALL crearDetalleServicio(7,7);
CALL crearDetalleServicio(8,8);
CALL crearDetalleServicio(9,9);
CALL crearDetalleServicio(10,10);
CALL crearDetalleServicio(12,11);
CALL crearDetalleServicio(13,12);
CALL crearDetalleServicio(14,13);
CALL crearDetalleServicio(15,14);
CALL crearDetalleServicio(16,15);
CALL crearDetalleServicio(17,16);
CALL crearDetalleServicio(18,17);
CALL crearDetalleServicio(19,18);
CALL crearDetalleServicio(20,1);
CALL crearDetalleServicio(21,2);
CALL crearDetalleServicio(22,3);
CALL crearDetalleServicio(23,4);
CALL crearDetalleServicio(24,5);
CALL crearDetalleServicio(25,6);
CALL crearDetalleServicio(26,7);
CALL crearDetalleServicio(27,8);
CALL crearDetalleServicio(28,9);
CALL crearDetalleServicio(29,10);
CALL crearDetalleServicio(30,11);
DELIMITER ;